laravel-rm/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();
Route::get('register', 'Auth\RegisterController@register'); // rota desativada
Route::post('register', 'Auth\RegisterController@postRegister'); // rota desativada

Route::get('criar-senha/{token}/{login}', ['as' => 'criar-senha', 'uses' => 'Auth\LoginController@getCriarSenha']);
Route::post('criar-senha', ['as' => 'gravar-senha', 'uses' => 'Auth\LoginController@postCriarSenha']);

Route::get('/', ['as' => 'home', 'uses' => 'CommonController@home']);

Route::get('aviso-de-privacidade', function(){ 
  if(App::getLocale() == 'en') {
    return view('common.politica-de-privacidade-en');
  }
  return view('common.politica-de-privacidade'); 
});

Route::get('lang/{locale}', function($locale) {
  if (in_array($locale, ['en', 'pt-br'])) Session::put('locale', $locale);
  return back();
});

Route::group([
  'middleware' => ['auth', 'auth.ativos']
], function () {
  Route::get('casos-2018', ['as' => 'blog-listagem', 'uses' => 'BlogController@listagem']);
  Route::get('casos-2018/{id}', ['as' => 'blog-detalhe', 'uses' => 'BlogController@detalhe']);
});

Route::group([
  'middleware' => ['auth.ativos', 'acesso_editor']
], function() {
  Route::resource('blog', 'BlogController');  
  Route::post('blog/reorder', 'BlogController@reorder');
});

Route::group([
'middleware' => ['auth.ativos', 'acesso_padrao']
], function(){
  Route::get('como-funciona', ['as' => 'como-funciona', 'uses' => 'CommonController@comoFunciona']);
  Route::get('regulamento', ['as' => 'regulamento', 'uses' => 'CommonController@regulamento']);
  Route::get('cronograma', ['as' => 'cronograma', 'uses' => 'CommonController@cronograma']);
  Route::get('avaliadores', ['as' => 'avaliadores', 'uses' => 'CommonController@avaliadores']);
  Route::get('consent-form', ['as' => 'user.consent', 'uses' => 'UserConsentController@form']);
  Route::post('consent-form', ['as' => 'user.consent.submit', 'uses' => 'UserConsentController@submit']);
});

Route::group([
  'middleware' => ['auth.ativos', 'acesso_medico_naoparticipante']
], function(){
  Route::get('apresentacao', ['as' => 'apresentacao', 'uses' => 'CommonController@apresentacao']);
});

Route::group([
'middleware' => ['auth.ativos', 'acesso_avaliador']
], function(){
  Route::get('avaliacoes', ['as' => 'avaliacoes', 'uses' => 'AvaliacoesController@index']);
  Route::get('buscar-avaliacoes', ['as' => 'buscar-avaliacoes', 'uses' => 'AvaliacoesController@buscar']);
  Route::post('enviar-notas', ['as' => 'avaliar', 'uses' => 'AvaliacoesController@enviarNotas']);
  Route::get('avaliation-case-data/{caso_codigo}', 'AvaliacoesController@caseData');
});

Route::group([
'middleware' => ['auth.ativos', 'envio_casos']
], function(){
  Route::get('preencher-caso/{categoria}', ['as' => 'preencher-caso', 'uses' => 'CasosController@preencherCaso']);
  Route::post('preencher-caso', ['as' => 'preencher-caso', 'uses' => 'CasosController@postPreencherCaso']);
  Route::post('preencher-caso-e-finalizar', ['as' => 'preencher-caso', 'uses' => 'CasosController@postPreencherCasoFinalizar']);
  Route::get('aviso-grupo', ['as' => 'aviso-grupo', 'uses' => 'GroupController@aviso']);
  Route::get('submeter-caso', ['as' => 'submeter-caso', 'uses' => 'CasosController@submeter']);
  Route::post('submeter-caso', ['as' => 'submeter-caso', 'uses' => 'CasosController@postSubmeter']);
  Route::get('download-formulario', ['as' => 'download-formulario', 'uses' => 'CasosController@downloadFormulario']);  
  Route::get('grupo', ['as' => 'grupo', 'uses' => 'GroupController@get']);
  Route::post('quill-img-upload', 'CasosController@quillImageUpload');
});

Route::group([
'middleware' => ['auth.ativos', 'acesso_admin']
], function(){

  Route::get('novos-casos', ['as' => 'novos-casos', 'uses' => 'AdminController@novosCasos']);
  Route::get('download-caso/{caso_codigo}', ['as' => 'download-caso', 'uses' => 'AdminController@downloadCaso']);
  Route::get('liberar-caso/{caso_codigo}', ['as' => 'liberar-caso', 'uses' => 'AdminController@liberarCaso']);
  Route::get('distribuir-caso/{caso_codigo}', ['as' => 'distribuir-caso', 'uses' => 'AdminController@distribuirCaso']);
  Route::get('excluir-caso/{caso_codigo}', ['as' => 'excluir-caso', 'uses' => 'AdminController@excluirCaso']);
  Route::get('pdf-caso/{caso_codigo}', ['as' => 'pdf-caso', 'uses' => 'AdminController@exportarPdfCaso']);
  Route::get('status-envios', ['as' => 'status-envios', 'uses' => 'AdminController@statusEnvios']);
  Route::get('historico', ['as' => 'historico', 'uses' => 'AdminController@historico']);
  Route::get('ranking', ['as' => 'ranking', 'uses' => 'AdminController@ranking']);

  Route::get('log-adesao', ['as' => 'usuarios-log-adesao', 'uses' => 'AdminController@logAdesaoAosTermos']);
  Route::get('usuarios', ['as' => 'usuarios-lista', 'uses' => 'AdminController@usuarios']);
  Route::get('ativar-usuario/{email}', 'AdminController@ativarUsuario');
  Route::get('iniciar-usuarios', 'AdminController@iniciarUsuarios');
  Route::post('encaminhar-casos', ['as' => 'encaminhar-casos', 'uses' => 'AdminController@encaminharFarmaco']);

  Route::get('gerenciar-grupos', ['as' => 'manage-groups.index', 'uses' => 'AdminGroupController@index']);
  Route::get('gerenciar-grupos/criar-grupo', ['as' => 'manage-groups.create', 'uses' => 'AdminGroupController@create']);
  Route::post('gerenciar-grupos/criar-grupo', ['as' => 'manage-groups.store', 'uses' => 'AdminGroupController@store']);
  Route::get('gerenciar-grupos/adicionar-integrante/{group_name}', ['as' => 'manage-groups.add-form', 'uses' => 'AdminGroupController@addForm']);
  Route::post('gerenciar-grupos/adicionar-integrante', ['as' => 'manage-groups.add', 'uses' => 'AdminGroupController@add']);
  Route::get('gerenciar-grupos/convidar/{group_name}', ['as' => 'manage-groups.invite', 'uses' => 'AdminGroupController@invite']);
  Route::get('gerenciar-grupos/remover/{coordenador_id}', ['as' => 'manage-groups.destroy', 'uses' => 'AdminGroupController@destroy']);
  Route::get('gerenciar-grupos/remover-medico/{medico_id}', ['as' => 'manage-groups.destroy-groupmember', 'uses' => 'AdminGroupController@destroyGroupMember']);

  Route::get('case-data/{caso_codigo}', 'AdminController@caseData');
  
  // Route::get('enviar-todos-casos', function(){
  //   $casos = RM\Models\Caso::all();
  //   foreach($casos as $x => $caso){
  //     echo $caso->id.' enviado<br>';
  //     //  ENVIAR CASO
  //     $ids = $caso->categoria.$caso->coordenador->id.$caso->id;
  //     $cod = 'C'.str_pad($ids, 6, '0', STR_PAD_LEFT);
  //     $caso->codigo = $cod;
  //     $caso->autor = 'Nome Autor teste#'.$x;
  //     $caso->enviado_em = Carbon\Carbon::now();

  //     $filename = $cod.'_'.Date('dmYHis').'.pdf';
  //     $caso->arquivo = $filename;
  //     $caso->excluido_em = null;
  //     $caso->save();
  //   }
  // });

  // Route::get('distribuir-todos', function(){
  //   $casos = RM\Models\Caso::all();
  //   foreach($casos as $x => $caso){
  //     echo $caso->id.' distribuido<br>';

  //     // DISTRIBUIR CASO
  //     $avaliadores = RM\Models\User::avaliadores()
  //                                     ->filtrarLocal($caso->coordenador->cidade)
  //                                     ->inRandomOrder()
  //                                     ->limit(3)
  //                                     ->get();


  //     if(count($avaliadores) != 3)
  //       return die('Não foi possível distribuir o caso clínico. (Erro: Total de avaliadores insuficiente (3), selecionados:'.count($avaliadores).')');

  //     foreach ($avaliadores as $avaliador) {
  //       // Gerar 1 registro de Avaliacao para cada avaliador
  //       $avaliacao = new RM\Models\Avaliacao(['casos_id' => $caso->id]);
  //       $avaliador->avaliacoes()->save($avaliacao);
  //     }

  //     $caso->distribuido_em = date('Y-m-d H:i:s');
  //     $caso->arquivo = null;
  //     $caso->save();
  //   }
  // });
  
});

laravel-rm/app/Models/Blog.php
<?php

namespace RM\Models;

use Illuminate\Database\Eloquent\Model;

class Blog extends Model
{
    protected $table = 'blog';

    protected $fillable = [
        'titulo',
        'slug',
        'embed',
        'texto',
        'titulo_caso_clinico',
        'texto_caso_clinico'
    ];

    protected $dates = [
        'created_at',
        'updated_at'
    ];

    public function scopeOrdenado($query) {
        return $query->orderBy('ordem');
    }
}

laravel-rm/app/Http/Controllers/BlogController.php
<?php

namespace RM\Http\Controllers;

use Auth;
use Session;
use RM\Models\Blog;
use Illuminate\Http\Request;

class BlogController extends Controller
{

    public function __construct()
    {
      $this->middleware(['auth', 'user_consent']);
    }

    public function listagem() {
      return view('blog.listagem', [
        'list' => Blog::ordenado()->get()
      ]);
    }

    public function detalhe($id) {
      return view('blog.detalhe', [
        'post' => Blog::findOrFail($id)
      ]);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
      return view('blog.index', [
        'list' => Blog::ordenado()->get()
      ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('blog.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        try {
            $post = new Blog;
            $post->fill($request->only([
                'titulo',
                'embed',
                'texto',
                'titulo_caso_clinico',
                'texto_caso_clinico'
            ]))->save();
            $request->session()->flash('sucesso', __('Post criado com sucesso!'));
            return redirect('blog');
        } catch(Exception $e) {
            $request->flash();

            $erro = logar_erro($e, Auth::user()->id);
            return back()->withErrors(array(__('Erro ao salvar postagem! (Erro: :err)', ['err' => $erro])));
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        return view('blog.edit', [
            'post' => Blog::findOrFail($id)
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        try {
            $post = Blog::findOrFail($id);
            $post->fill($request->only([
                'titulo',
                'embed',
                'texto',
                'titulo_caso_clinico',
                'texto_caso_clinico'
            ]))->save();
            $request->session()->flash('sucesso', __('Post atualizado com sucesso!'));
            return redirect('blog');
        } catch(Exception $e) {
            $request->flash();

            $erro = logar_erro($e, Auth::user()->id);
            return back()->withErrors(array(__('Erro ao salvar postagem! (Erro: :err)', ['err' => $erro])));
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        try {
            $post = Blog::findOrFail($id);
            $post->delete();
            Session::flash('sucesso', __('Post removido com sucesso!'));
            return redirect('blog');
        } catch(Exception $e) {
            Session::flash();

            $erro = logar_erro($e, Auth::user()->id);
            return back()->withErrors(array(__('Erro ao salvar postagem! (Erro: :err)', ['err' => $erro])));
        }
    }

    public function reorder(Request $request) {
        $itens = $request->data;
        
        for ($i = 0; $i < count($itens); $i++) {
            Blog::where('id', $itens[$i])->update([
                'ordem' => $i
            ]);
        }
    }
}

laravel-rm/resources/views/blog/create.blade.php
@extends('template.index')

@section('conteudo')

    <div class="lista-blog">
        <div class="centralizar">
            <h1>{{__('rm.BLOG_INCLUIR_EDITAR')}}</h1>

            @if($errors->any())
                <p class="alerta alerta-erro">
                    {{$errors->first()}}
                </p>
            @endif

            <form action="{{route('blog.store')}}" method="post" class="post">
                {!!csrf_field()!!}
                <h2>Vídeo</h2>
                <input type="text" name="titulo" placeholder="{{__('rm.BLOG_TITULO')}}">
                <input type="text" name="embed" placeholder="{{__('rm.BLOG_EMBED')}}">
                <textarea name="texto" placeholder="{{__('rm.BLOG_DESCRITIVO')}}"></textarea>
                <h2 class="section-title">Caso Clínico</h2>
                <input type="text" name="titulo_caso_clinico" placeholder="{{__('rm.TITULO')}}">
                <div id="editor"></div>
                <input type="hidden" name="texto_caso_clinico" id="texto_caso_clinico">
                <input type="submit" value="{{__('rm.BLOG_SALVAR')}}">
            </form>
        </div>
    </div>

@endsection

laravel-rm/resources/views/blog/detalhe.blade.php
@extends('template.index')

@section('conteudo')

<div class="detalhe-blog">
  <div class="centralizar">
    <h1>{{__('rm.BLOG')}}</h1>

    <a href="casos-2018" class="outros-videos">
      <img src="images/ico-voltar.png"> {{__('rm.OUTROS_VIDEOS')}}
    </a>
    
    <div class="coluna-blog">
      @if($post->embed)
        <div class="embed">
          {!!$post->embed!!}
        </div>
      @endif
      <h2>{{$post->titulo}}</h2>
      <div class="texto">
        <p>
          {!!nl2br($post->texto)!!}
        </p>
      </div>

      @if ($post->titulo_caso_clinico)
        <div class="texto-caso-clinico">
          <h2>{{$post->titulo_caso_clinico}}</h2>
          <div class="texto">{!!nl2br($post->texto_caso_clinico)!!}</div>
        </div>
      @endif
    </div>
  </div>
</div>

@endsection

laravel-rm/resources/views/blog/edit.blade.php
@extends('template.index')

@section('conteudo')

    <div class="lista-blog">
        <div class="centralizar">
            <h1>{{__('rm.BLOG_INCLUIR_EDITAR')}}</h1>

            @if($errors->any())
                <p class="alerta alerta-erro">
                    {{$errors->first()}}
                </p>
            @endif

            <form action="{{route('blog.update', ['id' => $post->id])}}" method="post" class="post">
                {!!csrf_field()!!}
                <input type="hidden" name="_method" value="PUT">
                <input type="text" name="titulo" placeholder="{{__('rm.BLOG_TITULO')}}" value="{{$post->titulo}}">
                <input type="text" name="embed" placeholder="{{__('rm.BLOG_EMBED')}}" value="{{$post->embed}}">
                <textarea name="texto" placeholder="{{__('rm.BLOG_DESCRITIVO')}}">{{$post->texto}}</textarea>
                <h2 class="section-title">Caso Clínico</h2>
                <input type="text" name="titulo_caso_clinico" placeholder="{{__('rm.TITULO')}}" value="{{$post->titulo_caso_clinico}}">
                <div id="editor">{!!$post->texto_caso_clinico!!}</div>
                <input type="hidden" name="texto_caso_clinico" id="texto_caso_clinico">
                <input type="submit" value="{{__('rm.BLOG_SALVAR')}}">
            </form>
        </div>
    </div>

@endsection

laravel-rm/resources/views/blog/index.blade.php
@extends('template.index')

@section('conteudo')

    <div class="lista-blog">
        <div class="centralizar">
            <h1>{{__('rm.BLOG')}}</h1>

            @if(session('sucesso'))
                <p class="alerta alerta-sucesso auto-close">
                    {{session('sucesso')}}
                </p>
            @endif
            
            <table class="table-sortable" id="table-sortable">
                @forelse($list as $post)
                    <tr class="tr-row" id="row_{{$post->id}}">
                        <td class='order'>
                            <a href="#" title="{{__('rm.ORDENAR')}}" class="btn-move">
                                <img src="images/ico-mover.png" alt="{{__('rm.ORDENAR')}}">
                            </a>
                        </td>
                        <td class='title'>{{$post->titulo or $post->titulo_caso_clinico}}</td>
                        <td class='edit'>
                            <a href="{{route('blog.edit', ['id' => $post->id])}}" title="{{__('rm.EDITAR')}}">
                                <img src="images/ico-editar.png" alt="{{__('rm.EDITAR')}}"> {{__('rm.EDITAR')}}
                            </a>
                        </td>
                        <td class='remove'>
                            <form action="{{route('blog.destroy', ['id' => $post->id])}}" method="POST">
                                {!!csrf_field()!!}
                                <input type="hidden" name="_method" value="DELETE">
                                <button title="{{__('rm.EDITAR')}}">
                                    <img src="images/ico-excluir.png" alt="{{__('rm.EDITAR')}}"> {{__('rm.EXCLUIR')}}
                                </button>
                            </form>                            
                        </td>
                    </tr>
                @empty
                    <tr>
                        <td><p class="nenhum-post">{{__('rm.NENHUM_POST')}}</p></td>
                    </tr>
                @endforelse
            </table>
        </div>
    </div>

@endsection

laravel-rm/resources/views/blog/listagem.blade.php
@extends('template.index')

@section('conteudo')

<div class="lista-blog">
  <div class="centralizar blog-cell-list">
    <div class="blog-cell">
      <h1>{{__('rm.CONTEUDO_RELACIONADO')}}</h1>
      <p>{{__('rm.INSPIRE-SE')}}</p>
    </div>
    @forelse($list as $post)
      <div class="blog-cell">
        <a href="casos-2018/{{$post->id}}" title="{{$post->titulo}}">
          @if($post->embed)
            <div class="blog-thumb-container">
              <div class="blog-thumb-wrapper">
                  <div class="blog-thumb">
                    {!!youtube_embed_to_thumbnail($post->embed)!!}
                  </div>
              </div>
            </div>
          @endif
          <h2>{{$post->titulo or $post->titulo_caso_clinico}}</h2>
        </a>
      </div>
    @empty
        <tr>
            <td><p class="nenhum-post">{{__('rm.NENHUM_POST')}}</p></td>
        </tr>
    @endforelse
  </div>
</div>

@endsection